name: Runner tests

on:
  push:
    paths:
      - 'tests/**'
      - 'run.sh'
      - 'test.sh'
      - 'process.py'
  pull_request:
    paths:
      - 'tests/**'
      - 'run.sh'
      - 'test.sh'
      - 'process.py'

jobs:
  runner-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch everything
        run: git fetch --prune --unshallow

      - name: Run tests
        shell: bash
        run: ./test.sh
